// Vercel serverless function: POST /api/mood
// Takes a room's basic stats + a free-text "mood" description from the
// Instant Lighting Guide and returns 2-4 short, practical lighting/
// automation suggestions generated by Claude.
//
// Requires the ANTHROPIC_API_KEY environment variable to be set in the
// Vercel project (Project Settings -> Environment Variables). If it's
// missing or the API call fails, this returns a 500 / non-OK response,
// and the front-end (assets/calculator.js) automatically falls back to
// its built-in local suggestion engine — so the site keeps working even
// if this function isn't configured yet.

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: 'ANTHROPIC_API_KEY not configured' });
    return;
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch (e) { body = {}; }
  }
  body = body || {};

  const roomLabel = String(body.roomLabel || body.roomType || 'room').slice(0, 60);
  const area = Number(body.area) || 0;
  const ceiling = Number(body.ceiling) || 0;
  const lux = Number(body.lux) || 0;
  const cct = String(body.cct || '').slice(0, 60);
  const mood = String(body.mood || '').slice(0, 400);

  if (!mood.trim()) {
    res.status(400).json({ error: 'mood is required' });
    return;
  }

  const prompt =
    'You are a residential lighting and home-automation design assistant for ' +
    '"OnePoint Smart Home". A customer is using the free Instant Lighting Guide ' +
    'and described the mood they want for one room.\n\n' +
    'Room: ' + roomLabel + ' (' + area + ' sq ft, ' + ceiling + ' ft ceiling)\n' +
    'Baseline recommended light level: ' + lux + ' lux, ' + cct + '\n' +
    'Desired mood (in the customer\'s own words): "' + mood + '"\n\n' +
    'Suggest 2-4 short, practical lighting and home-automation ideas (each under ' +
    '20 words) that would help achieve this mood in this room — e.g. specific ' +
    'colour temperatures/CCT, dimming scenes, accent/cove/wall lighting, smart ' +
    'switches or automations, time-of-day scenes. Be concrete and avoid generic ' +
    'filler. Respond with ONLY a JSON array of strings, no other text, e.g. ' +
    '["suggestion one", "suggestion two"].';

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 400,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      res.status(502).json({ error: 'Anthropic API error', detail: errText.slice(0, 300) });
      return;
    }

    const data = await response.json();
    const text = (data.content && data.content[0] && data.content[0].text) || '[]';

    let suggestions;
    try {
      // The model may wrap the JSON in markdown fences or add stray text —
      // pull out the first [...] block before parsing.
      const match = text.match(/\[[\s\S]*\]/);
      suggestions = JSON.parse(match ? match[0] : text);
    } catch (e) {
      suggestions = [];
    }

    if (!Array.isArray(suggestions)) suggestions = [];
    suggestions = suggestions
      .filter(function (s) { return typeof s === 'string' && s.trim(); })
      .slice(0, 4);

    if (suggestions.length === 0) {
      res.status(502).json({ error: 'No suggestions returned' });
      return;
    }

    res.status(200).json({ suggestions: suggestions });
  } catch (err) {
    res.status(500).json({ error: 'Request failed', detail: String(err && err.message || err) });
  }
};
